version: "2"
linters:
  enable:
    - loglint
  settings:
    custom:
      loglint:
        path: ./loglint.so
        description: Linter for log messages
        settings:
          config_path: ./config/config.yaml
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

